# Generated by Django 5.2.16 on 2026-07-31 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inbox', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='draftapproval',
            name='invalidated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='draftapproval',
            name='invalidated_reason',
            field=models.CharField(blank=True, max_length=120),
        ),
    ]
