# Generated by Django 5.2.16 on 2026-07-31 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inbox', '0002_draftapproval_invalidated_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='domain',
            name='hostname',
            field=models.CharField(max_length=253),
        ),
        migrations.AddConstraint(
            model_name='domain',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'DISABLED'), _negated=True), fields=('hostname',), name='uniq_active_domain_hostname'),
        ),
    ]
