# Generated by Django 5.2.16 on 2026-07-31 20:37

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inbox', '0003_alter_domain_hostname_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SignupAttempt',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('fingerprint_hash', models.CharField(db_index=True, max_length=64)),
                ('email_hash', models.CharField(db_index=True, max_length=64)),
                ('accepted', models.BooleanField(default=False)),
            ],
            options={
                'indexes': [models.Index(fields=['fingerprint_hash', '-created_at'], name='inbox_signu_fingerp_c51b87_idx')],
            },
        ),
    ]
