# Generated by Django 5.2.16 on 2026-08-02 13:46

from django.db import migrations, models


def mark_existing_subscriptions_as_pro(apps, schema_editor):
    BillingProfile = apps.get_model('inbox', 'BillingProfile')
    BillingProfile.objects.filter(stripe_subscription_id__isnull=False).update(
        subscription_plan='pro'
    )


class Migration(migrations.Migration):

    dependencies = [
        ('inbox', '0006_stripewebhookevent_billingprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='billingprofile',
            name='subscription_plan',
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.RunPython(mark_existing_subscriptions_as_pro, migrations.RunPython.noop),
    ]
