# Generated by Django 5.2.16 on 2026-08-09

from django.db import migrations, models


def mark_existing_inbound_messages_viewed(apps, schema_editor):
    Message = apps.get_model("inbox", "Message")
    inbound_messages = Message.objects.filter(direction="INBOUND", viewed_at__isnull=True)
    for message in inbound_messages.iterator(chunk_size=1000):
        message.viewed_at = message.received_at
        message.save(update_fields=("viewed_at",))


class Migration(migrations.Migration):
    dependencies = [
        ("inbox", "0007_billingprofile_subscription_plan"),
    ]

    operations = [
        migrations.AddField(
            model_name="conversation",
            name="archived_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="conversation",
            name="starred_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="conversation",
            name="trashed_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="conversation",
            name="work_started_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="message",
            name="viewed_at",
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AddIndex(
            model_name="conversation",
            index=models.Index(
                fields=["domain", "trashed_at", "archived_at", "-last_message_at"],
                name="inbox_conve_domain__3932b5_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="message",
            index=models.Index(
                fields=["domain", "direction", "viewed_at"],
                name="inbox_messa_domain__8dfcf6_idx",
            ),
        ),
        migrations.RunPython(
            mark_existing_inbound_messages_viewed,
            migrations.RunPython.noop,
        ),
    ]
