# Generated by Django 5.2.16 on 2026-08-10 08:13

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


def _replace_scope(apps, old, new):
    api_token = apps.get_model("inbox", "APIToken")
    for token in api_token.objects.all().iterator():
        scopes = [new if scope == old else scope for scope in token.scopes]
        if scopes != token.scopes:
            token.scopes = sorted(set(scopes))
            token.save(update_fields=("scopes",))
    for model_name in ("Grant", "AccessToken", "IDToken", "DeviceGrant"):
        model = apps.get_model("oauth2_provider", model_name)
        for record in model.objects.all().iterator():
            scopes = record.scope.split()
            updated = [new if scope == old else scope for scope in scopes]
            if updated != scopes:
                record.scope = " ".join(dict.fromkeys(updated))
                record.save(update_fields=("scope",))


def forwards(apps, schema_editor):
    _replace_scope(apps, "approve_send", "send")


def backwards(apps, schema_editor):
    _replace_scope(apps, "send", "approve_send")


class Migration(migrations.Migration):

    dependencies = [
        ('inbox', '0009_conversation_tags'),
        ('oauth2_provider', '0020_cimd_application_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='outboundmessage',
            name='authorization_mode',
            field=models.CharField(choices=[('OWNER_APPROVAL', 'Owner approval'), ('DELEGATED_SCOPE', 'Delegated send scope')], default='OWNER_APPROVAL', max_length=24),
        ),
        migrations.CreateModel(
            name='OutboundControl',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_paused', models.BooleanField(default=False)),
                ('paused_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='outbound_control', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RunPython(forwards, backwards),
    ]
