# Generated by Django 5.2.16 on 2026-08-13 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inbox', '0012_billingprofile_domain_capacity_grace'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditevent',
            name='request_id',
            field=models.CharField(db_index=True, max_length=96),
        ),
    ]
